// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zenosxbjtwfkhyahbjyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inplbm9zeGJqdHdma2h5YWhianlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjcxMTYsImV4cCI6MjA2NjEwMzExNn0.JFBpM6ZU5V3FIOfjUqRF1sPug2b4OubH-qSKViurHHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);